### ISSUE TITLE
walls

### ISSUE THREAD

**Issue by aleksejalex** [EruditeCode/3D_python#1]
I'm not sure it's an issue, more like a question. The particle in 'maze_builder.py' and other programs can pass through the walls of maze. 

Would it be possible to change that (so particle would collide and would not be able to go through walls)? If yes, how?

**Comment by EruditeCode** [comment]
This is a great question! I did deliberately not put in a collider (mainly for making filming a bit easier). However, you could add a collision_check function within the particle class which takes the walls as an argument and checks if the wall is within the radius of the particle if the position is updated. If it does, then skip the position update. The method of collision detection would be determining the length of the line that intersects the wall from the circle centre at 90 degrees, if this line is <= radius of the circle then a collision has occurred. You could also use Heron's formula to find the height of the triangle between the two wall ends and the circle centre (this would be the same as the perpendicular line).

I'm also going to release a video/update to this project in a few days (if I get enough free evenings :D) which will address the fisheye distortion and add some textures (though somewhat inefficiently).

I hope that's helpful and once again thanks for the question!

**Comment by aleksejalex** [comment]
Thank you for detailed answer. I'm not very familiar with PyGame yet, but (as soon as I'll have a free evening ;-) ) I will definitely try to modify it according to your comment.
